name: docker
on:
  push:
    branches: [master]
    tags: [v*]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: deathspike/normalasser
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          labels: ${{steps.meta.outputs.labels}}
          tags: ${{steps.meta.outputs.tags}}
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: deathspike/normalasser
